version: "3"
services:
  plurk_bot:
    environment:
      TZ: "Asia/Taipei"
    volumes:
      - ./data:/app/data
      - ./token.txt:/app/token.txt
    image: ghcr.io/dephilia/siaosih_bot:latest
    restart: always
